services:
  quizoutserver:
    environment:
      - SECRET_LOCATION=/run/secrets/
      - DEBUG=True
    build: .
    expose:
      - 8000
    secrets:
      - api_key
      - api_secret
      - db_pass
    volumes:
      - quizout-data:/app/db.sqlite
  web:
    image: nginx
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/templates:/etc/nginx/templates
      - ./app/static:/var/www/static
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
secrets:
  api_key:
    file: ~/.quizoutserver/secrets/api_key
  api_secret:
    file: ~/.quizoutserver/secrets/api_secret
  db_pass:
    file: ~/.quizoutserver/secrets/db_pass
volumes:
  quizout-data:
