"""buzzer_client table

Revision ID: 13df7a1ecda5
Revises: 413e6292b8dd
Create Date: 2025-07-25 23:35:46.436304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13df7a1ecda5'
down_revision = '413e6292b8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buzzer_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=25), nullable=False),
    sa.Column('teamBuzzerInfo', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buzzer_client')
    # ### end Alembic commands ###
